# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           my_rust_app
Version:        0.1.0
Release:        %autorelease
Summary:        A boilerplate template application get started with GTK, Rust, Meson, Flatpak made for GNOME

License:        MIT 

URL:            https://github.com/timlau/my_rust_app
Source:         %{name}-%{version}.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  meson
BuildRequires: desktop-file-utils
BuildRequires: libappstream-glib

%global _description %{expand:
%{summary}.}

%description %{_description}

%generate_buildrequires
%cargo_generate_buildrequires

%prep
%autosetup -n %{name}-%{version} -p1
%cargo_prep

%check
appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/*.metainfo.xml
desktop-file-validate %{buildroot}/%{_datadir}/applications/*.desktop

%conf
%meson

%build
%meson_build

%install
%meson_install

%post
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
glib-compile-schemas /usr/share/glib-2.0/schemas/ &>/dev/null || :

%postun
if [ $1 -eq 0 ] ; then
    /bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null
    /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi

%files
%license LICENSE
%doc README.md
%doc meson_options.txt
%{_datadir}/%{name}/
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/symbolic/apps/*.svg
%{_datadir}/icons/hicolor/scalable/apps/*.svg
%{_metainfodir}/*.metainfo.xml
%{_datadir}/glib-2.0/schemas/*.gschema.xml
%{_bindir}/my_rust_app

%changelog
%autochangelog
