# RPM spec file for Rust application acoirdin to Fedora Packaging Guidelines
#
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
#
# It is a little different, because we are using meson as build system

# Generated by rust2rpm 27
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

Name:           my_rust_app
Version:        0.1.0
Release:        %autorelease
Summary:        A boilerplate template application get started with GTK, Rust, Meson, Flatpak made for GNOME

# Licenses found in the project and their dependencies
License:        MIT AND Apache-2.0 AND Unicode-DFS-2016 AND Zlib

# (MIT OR Apache-2.0) AND Unicode-DFS-2016
# Apache-2.0
# Apache-2.0 OR MIT
# MIT
# MIT OR Apache-2.0
# Unlicense OR MIT
# Zlib


URL:            https://github.com/timlau/my_rust_app
Source:         %{name}-%{version}.tar.xz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  meson
BuildRequires:  desktop-file-utils
BuildRequires:  libappstream-glib

%global _description %{expand:
%{summary}.}

%description %{_description}

%generate_buildrequires
%cargo_generate_buildrequires


%prep
%autosetup -n %{name}-%{version} -p1
%cargo_prep

%check
appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/*.metainfo.xml
desktop-file-validate %{buildroot}/%{_datadir}/applications/*.desktop
# no cargo_test, there is no tests defined in this project

%conf
%meson

%build
%meson_build
%cargo_license_summary
%cargo_license

%install
%meson_install

%post
/bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :
glib-compile-schemas /usr/share/glib-2.0/schemas/ &>/dev/null || :

%postun
if [ $1 -eq 0 ] ; then
    /bin/touch --no-create %{_datadir}/icons/hicolor &>/dev/null
    /usr/bin/gtk-update-icon-cache %{_datadir}/icons/hicolor &>/dev/null || :
fi

%files
%license LICENSE
%doc README.md
%doc meson_options.txt
%{_datadir}/%{name}/
%{_datadir}/applications/*.desktop
%{_datadir}/icons/hicolor/symbolic/apps/*.svg
%{_datadir}/icons/hicolor/scalable/apps/*.svg
%{_metainfodir}/*.metainfo.xml
%{_datadir}/glib-2.0/schemas/*.gschema.xml
%{_bindir}/my_rust_app

%changelog
%autochangelog
